[package]
name = "secret_loader"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
serde_json = "1"
rpassword = "7"
tokio = { version = "1", features = ["full"] }